# Dirs
zabbix_service_dir: "{{ services_path }}/zabbix"
zabbix_data_dir: "{{ zabbix_service_dir }}/data"
zabbix_credentials_dir: "{{ zabbix_service_dir }}/credentials"

# Image
zabbix_image_tag: "7.4-latest"

# Ports
zabbix_web_port: "5050"

# Timezone
zabbix_timezone: "Europe/Minsk"

# Vault
zabbix_vault_path: infra/zabbix
zabbix_vault_secrets:
  - ansible_name: zabbix_db_password
    vault_name: db_password
    generator: "{{ lookup('pipe', 'openssl rand -hex 16') }}"
  - ansible_name: zabbix_admin_password
    vault_name: admin_password
    generator: "{{ lookup('pipe', 'openssl rand -hex 16') }}"