- name: Enable KV v2 secret engine
  shell: |
    docker exec -e VAULT_TOKEN={{ vault_token }} vault \
      vault secrets enable -path={{ vault_kv_engine }} kv-v2
  register: result
  changed_when: "'Success' in result.stdout or 'enabled' in result.stdout"
  failed_when: 
    - result.rc != 0
    - "'already in use' not in result.stderr"
  no_log: true

- name: Enable AppRole auth method
  shell: |
    docker exec -e VAULT_TOKEN={{ vault_token }} vault \
     vault auth enable approle
  register: result
  changed_when: "'Success' in result.stdout or 'enabled' in result.stdout"
  failed_when: 
    - result.rc != 0
    - "'already in use' not in result.stderr"
  no_log: true

- name: Enable userpass auth method
  shell: |
    docker exec -e VAULT_TOKEN={{ vault_token }} vault \
      vault auth enable userpass
  register: userpass_enable
  changed_when: "'Success!' in userpass_enable.stdout"
  failed_when: 
    - userpass_enable.rc != 0
    - "'already in use' not in userpass_enable.stderr"
  no_log: true