- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ zabbix_service_dir }}"
    - "{{ zabbix_data_dir }}"
    - "{{ zabbix_credentials_dir }}"

- name: Write zabbix db password file
  copy:
    content: "POSTGRES_PASSWORD={{ zabbix_db_password }}"
    dest: "{{ zabbix_service_dir }}/zabbix.env"
    mode: "0600"
  no_log: true

- name: Create Docker Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ zabbix_service_dir }}/docker-compose.yml"
    mode: "0644"

- name: Start zabbix stack
  community.docker.docker_compose_v2:
    project_src: "{{ zabbix_service_dir }}"
    state: present
    wait: true