- name: Init zabbix secrets in vault
  include_role:
    name: vault
    tasks_from: init_services_secrets_templates/generate_init_secrets
  vars:
    vault_log_service_name: "zabbix"
    vault_service_secrets_path: "{{ zabbix_vault_path }}"
    vault_service_secrets: "{{ zabbix_vault_secrets }}"