- name: Login to vault
  include_role:
    name: vault
    tasks_from: login
  tags:
    - always

- name: Get zabbix secrets
  include_role:
    name: zabbix
    tasks_from: read_vault_secrets
  tags:
    - always

- name: Prepare agent
  include_tasks: 
    file: deploy/agent_prepare.yml
    apply:
      tags: zabbix-agent
  tags: zabbix-agent

- name: Install zabbix
  include_tasks: 
    file: deploy/install.yml
    apply:
      tags: zabbix-install
  tags: zabbix-install

- name: Configure agent plugins
  include_tasks: 
    file: deploy/configure_plugins.yml
    apply:
      tags: zabbix-plugins
  tags: zabbix-plugins

- name: Configure zabbix server
  include_tasks: 
    file: deploy/configure_server.yml
    apply:
      tags: zabbix-server
  tags: zabbix-server