- name: Read zabbix secrets
  include_role:
    name: vault
    tasks_from: init_services_secrets_templates/read_init_secrets
    apply:
      tags: always
  vars:
    vault_log_service_name: "zabbix"
    vault_service_secrets_path: "{{ zabbix_vault_path }}"
    vault_service_secrets: "{{ zabbix_vault_secrets }}"
  tags: always