- name: Load step_ca vars
  include_vars:
    file: "{{ service_playbook_dir }}/vars.yml"

- name: Check if step_ca secrets already exist
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ vault_kv_engine }}"
    path: "infra/{{ service_name }}"
  register: step_ca_secrets
  failed_when: false
  no_log: true

- name: Generate and sate secrets
  block:
    - name: Init secrets accumulator
      set_fact:
        step_ca_secret_files:
          fingerprint:     "{{ step_ca_fingerprint_file }}"
          init_password:   "{{ step_ca_init_password_file }}"
          root_ca:         "{{ step_ca_root_ca_file }}"
          intermediate_ca: "{{ step_ca_intermediate_ca_file }}"

    - name: Read step_ca secret files
      slurp:
        src: "{{ item.value }}"
      register: step_ca_files_raw
      loop: "{{ step_ca_secret_files | default({}) | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Build step_ca secrets dict
      set_fact:
        step_ca_secrets_data: >-
          {{
            dict(
              step_ca_files_raw.results
              | map(attribute='item.key')
              | zip(
                  step_ca_files_raw.results
                  | map(attribute='content')
                  | map('b64decode')
                )
            )
          }}

    - name: Write step_ca secrets if missing
      community.hashi_vault.vault_kv2_write:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_kv_engine }}"
        path: "infra/{{ service_name }}"
        data: "{{ step_ca_secrets_data }}"

  when: step_ca_secrets.data is not defined
  no_log: true