- name: Add service to garage (create bucker, add creds)
  hosts: all
  become: yes
  pre_tasks:
    - name: Preflight checks
      include_role:
        name: preflight
      vars:
        preflight_required_vars:
          - service_name
          - vault_ansible_role_id
          - vault_ansible_secret_id
  tasks:
    - name: Add garage service
      include_role:
        name: garage
        tasks_from: add_service