- name: Deploy Garage
  hosts: all
  become: yes
  pre_tasks:
    - name: Preflight checks
      include_role:
        name: preflight
      vars:
        preflight_required_vars:
          - vault_ansible_role_id
          - vault_ansible_secret_id
  tasks:
    - name: Deploy garage
      include_role:
        name: garage
        tasks_from: deploy