- name: Read existing garage secrets
  include_role:
    name: garage
    tasks_from: _read_vault_secrets

- name: Generate and write garage secrets if missing
  community.hashi_vault.vault_kv2_write:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ vault_kv_engine }}"
    path: "{{ garage_vault_path }}"
    data: >-
      {{
        dict(
          garage_vault_secrets
          | map(attribute='vault_name')
          | zip(
              garage_vault_secrets
              | map(attribute='generator')
            )
        )
      }}
  when: not garage_secrets_exist
  no_log: true