- name: Read garage secrets from vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ vault_kv_engine }}"
    path: "{{ garage_vault_path }}"
  register: garage_secrets
  failed_when: false
  no_log: true

- name: Expose garage secrets as facts
  set_fact:
    "{{ garage_secret.ansible_name }}": "{{ garage_secrets.secret[garage_secret.vault_name] | default('') }}"
  loop: "{{ garage_vault_secrets }}"
  loop_control:
    label: "{{ garage_secret.ansible_name }}"
    loop_var: garage_secret
  when: garage_secrets.data is defined
  no_log: true

- name: Set garage_secrets_exist flag
  set_fact:
    garage_secrets_exist: "{{ garage_secrets.data is defined }}"
  no_log: true