- name: Read garage secrets from vault
  include_role:
    name: vault
    tasks_from: init_services_secrets_templates/read_init_secrets
  vars:
    vault_log_service_name: "garage"
    vault_service_secrets_path: "{{ garage_vault_path }}"
    vault_service_secrets: "{{ garage_vault_secrets }}"