- name: Init secrets accumulator
  set_fact:
    step_ca_secret_files:
      fingerprint:     "{{ step_ca_fingerprint_file }}"
      init_password:   "{{ step_ca_init_password_file }}"
      root_ca:         "{{ step_ca_root_ca_file }}"
      intermediate_ca: "{{ step_ca_intermediate_ca_file }}"

- name: Read step_ca secret files
  slurp:
    src: "{{ step_ca_secret_file.value }}"
  register: step_ca_files_raw
  loop: "{{ step_ca_secret_files | default({}) | dict2items }}"
  loop_control:
    label: "{{ step_ca_secret_file.key }}"
    loop_var: step_ca_secret_file
  no_log: true

- name: Build step_ca secrets dict
  set_fact:
    step_ca_secrets_data: >-
      {{
        dict(
          step_ca_files_raw.results
          | map(attribute='step_ca_secret_file.key')
          | zip(
              step_ca_files_raw.results
              | map(attribute='content')
              | map('b64decode')
            )
        )
      }}
  no_log: true

- name: Write step_ca secrets if missing
  community.hashi_vault.vault_kv2_write:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ vault_kv_engine }}"
    path: "{{ garage_vault_path }}"
    data: "{{ step_ca_secrets_data }}"
  no_log: true