- name: Init step_ca secrets in vault
  include_role:
    name: vault
    tasks_from: init_services_secrets_templates/slurp_init_secrets
  vars:
    vault_log_service_name: "step_ca"
    vault_service_secrets_path: "{{ step_ca_vault_path }}"
    vault_service_secrets: "{{ step_ca_vault_secrets }}"