- name: Read step_ca secret files
  slurp:
    src: "{{ step_ca_secret_file.file }}"
  register: step_ca_files_raw
  loop: "{{ step_ca_vault_secrets }}"
  loop_control:
    label: "{{ step_ca_secret_file.vault_name }}"
    loop_var: step_ca_vault_secrets
  no_log: true

- name: Build step_ca secrets dict
  set_fact:
    step_ca_secrets_data: >-
      {{
        dict(
          step_ca_files_raw.results
          | map(attribute='step_ca_vault_secrets.vault_name')
          | zip(
              step_ca_files_raw.results
              | map(attribute='content')
              | map('b64decode')
            )
        )
      }}
  no_log: true

- name: Write step_ca secrets if missing
  community.hashi_vault.vault_kv2_write:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ vault_kv_engine }}"
    path: "{{ step_ca_vault_path }}"
    data: "{{ step_ca_secrets_data }}"
  no_log: true