- name: Read step_ca secrets from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ vault_kv_engine }}"
    path: "{{ step_ca_vault_path }}"
  register: step_ca_secrets_raw
  failed_when: false
  no_log: true

- name: Expose step_ca secrets as facts
  set_fact:
    "{{ step_ca_secret.ansible_name }}": "{{ step_ca_secrets_raw.secret[step_ca_secret.vault_name] | default('') }}"
  loop: "{{ step_ca_vault_secrets }}"
  loop_control:
    label: "{{ step_ca_secret.ansible_name }}"
    loop_var: step_ca_secret
  when: step_ca_secrets_raw.data is defined
  no_log: true

- name: Set step_ca_secrets_exist flag
  set_fact:
    step_ca_secrets_exist: "{{ step_ca_secrets_raw.data is defined }}"
  no_log: true