- name: Read and set garage secrets
  block:
    - name: Read garage secrets from vault
      community.hashi_vault.vault_kv2_get:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        engine_mount_point: "{{ vault_kv_engine }}"
        path: "infra/garage"
      become: false
      register: garage_secrets
      no_log: true

    - name: Set garage secrets facts
      set_fact:
        garage_admin_token: "{{ garage_secrets.secret.admin_token }}"
        garage_rpc_secret: "{{ garage_secrets.secret.rpc_secret }}"
      no_log: true

  tags: always