- name: Read technitium api token
  include_role:
    name: vault
    tasks_from: init_services_secrets_templates/read_init_secrets
    apply:
      tags: always
  vars:
    vault_log_service_name: "dnsweaver"
    vault_service_secrets_path: "{{ technitium_vault_path }}"
    vault_service_secrets: "{{ technitium_vault_secrets }}"
  tags: always