- name: Read traefik secrets from vault
  include_role:
    name: vault
    tasks_from: init_services_secrets_templates/read_init_secrets
  vars:
    vault_log_service_name: "traefik"
    vault_service_secrets_path: "{{ traefik_vault_path }}"
    vault_service_secrets: "{{ traefik_vault_secrets }}"