- name: Vault login
  block:
    - name: Login to vault as ansible
      community.hashi_vault.vault_login:
        url: "{{ vault_addr }}"
        auth_method: approle
        role_id: "{{ vault_ansible_role_id }}"
        secret_id: "{{ vault_ansible_secret_id }}"
      register: vault_login_result
      become: false
      no_log: true

    - name: Set vault_token fact
      set_fact:
        vault_token: "{{ vault_login_result.login.auth.client_token }}"
      no_log: true

  tags: always