- name: Init technitium secrets in vault
  include_role:
    name: vault
    tasks_from: init_services_secrets_templates/generate_init_secrets
  vars:
    vault_log_service_name: "technitium"
    vault_service_secrets_path: "{{ technitium_vault_path }}"
    vault_service_secrets: "{{ technitium_vault_secrets }}"