- name: Add service to Vault
  hosts: all
  become: yes
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
  pre_tasks:
    - name: Preflight checks
      include_role:
        name: preflight
      vars:
        preflight_required_vars:
          - service_name
          - vault_ansible_role_id
          - vault_ansible_secret_id
  tasks:
    - name: Add vault service
      include_role:
        name: vault
        tasks_from: add_service