- name: Deploy Vault
  hosts: all
  become: yes
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
  pre_tasks:
    - name: Preflight checks
      include_role:
        name: preflight
      vars:
        preflight_required_vars:
          - vault_admin_password
  tasks:
    - name: Deploy vault
      include_role:
        name: vault
        tasks_from: deploy