- name: Init services secrets
  hosts: all
  become: true
  pre_tasks:
    - name: Preflight checks
      include_role:
        name: preflight
      vars:
        preflight_required_vars:
          - vault_ansible_role_id
          - vault_ansible_secret_id
  tasks:
    - name: Init services secrets
      include_role:
        name: vault
        tasks_from: init_services_secrets