- name: Init services secrets
  hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Login to vault
      include_role:
        name: vault/login

    - name: Find _init_vault_secrets_task files
      find:
        paths: "{{ playbook_dir | dirname }}"
        patterns: "_init_vault_secrets_task.yml"
        file_type: file
        recurse: true
      delegate_to: localhost
      become: false
      register: init_files

    - name: Init vault secrets for each service
      include_tasks: "{{ item.path }}"
      loop: "{{ init_files.files }}"
      loop_control:
        label: "{{ item.path | dirname | basename }}"
      vars:
        service_name: "{{ item.path | dirname | basename }}"
        service_playbook_dir: "{{ item.path | dirname }}"