- name: Install hvac library
  pip:
    name: hvac
    state: present
    virtualenv: "{{ ansible_venv_path }}"
  tags: always

- name: Validate tls certificate if enabled
  include_tasks: 
    file: deploy/tls.yml
    apply:
      tags: vault-tls
  tags: vault-tls
  when: not vault_tls_disable | bool

- name: Install Vault
  include_tasks: 
    file: deploy/install.yml
    apply:
      tags: vault-install
  tags: vault-install

- name: Initialize Vault
  include_tasks: 
    file: deploy/init.yml
    apply:
      tags: vault-init
  tags: vault-init

- name: Unseal Vault
  include_tasks: 
    file: deploy/unseal.yml
    apply:
      tags: vault-unseal
  tags: vault-unseal

- name: Prepare token for next tasks
  include_tasks: 
    file: deploy/prepare_token.yml
    apply:
      tags: always
  tags: always

- name: Configure Vault
  include_tasks: 
    file: deploy/configure.yml
    apply:
      tags: vault-configure
  tags: vault-configure

- name: Create admin creds
  include_tasks: 
    file: deploy/admin.yml
    apply:
      tags: vault-admin
  tags: vault-admin

- name: Create ansible token
  include_tasks: 
    file: deploy/ansible.yml
    apply:
      tags: vault-ansible
  tags: vault-ansible