- name: Login to vault
  include_role:
    name: vault
    tasks_from: login

- name: Find _init_vault_secrets files in roles
  find:
    paths: "{{ role_path | dirname }}"
    patterns: "_init_vault_secrets.yml"
    file_type: file
    recurse: true
  delegate_to: localhost
  run_once: true
  become: false
  register: init_files

- name: Init vault secrets for each service
  include_role:
    name: "{{ item.path | dirname | dirname | basename }}"
    tasks_from: _init_vault_secrets
  loop: "{{ init_files.files }}"
  loop_control:
    label: "{{ item.path | dirname | dirname | basename }}"