- name: Login to vault
  include_role:
    name: vault
    tasks_from: login

- name: Find _init_vault_secrets files in roles
  find:
    paths: "{{ role_path | dirname }}"
    patterns: "_init_vault_secrets.yml"
    file_type: file
    recurse: true
  delegate_to: localhost
  run_once: true
  become: false
  register: init_files

- name: Filter init files by allowed roles
  set_fact:
    filtered_init_files: >-
      {{
        init_files.files
        | selectattr('path', 'search', '/' ~ item ~ '/')
        | list
      }}
  loop: "{{ vault_init_roles }}"
  when: vault_init_roles | length > 0
  run_once: true

- name: Init vault secrets for each service
  include_role:
    name: "{{ item.path | dirname | dirname | basename }}"
    tasks_from: _init_vault_secrets
  loop: "{{ filtered_init_files }}"
  loop_control:
    label: "{{ item.path | dirname | dirname | basename }}"