- name: "[{{ vault_log_service_name }}] Validate required params"
  assert:
    that:
      - vault_log_service_name | length > 0
      - vault_token | length > 0
      - vault_service_secrets_path | length > 0
      - vault_service_secrets is iterable
      - vault_service_secrets | length > 0
      - vault_service_secrets | selectattr('vault_name', 'undefined') | length == 0
      - vault_service_secrets | selectattr('ansible_name', 'undefined') | length == 0
    fail_msg: >-
      vault_service_secrets_path is required, vault_service_secrets must be array of {vault_name: "", ansible_name: ""}

- name: "[{{ vault_log_service_name }}] Read secrets from vault"
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_addr }}"
    ca_cert: "{{ step_ca_system_ca_path }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ vault_kv_engine }}"
    path: "{{ vault_service_secrets_path }}"
  register: vault_fetched_secrets
  failed_when: vault_fetched_secrets.data is not defined
  no_log: true

- name: "[{{ vault_log_service_name }}] Expose secrets as facts"
  set_fact:
    "{{ vault_secret.ansible_name }}": "{{ vault_fetched_secrets.secret[vault_secret.vault_name] | default('') }}"
  loop: "{{ vault_service_secrets }}"
  loop_control:
    label: "{{ vault_secret.ansible_name }}"
    loop_var: vault_secret
  no_log: true