- name: "[{{ vault_log_service_name }}] Validate required params"
  assert:
    that:
      - vault_log_service_name | length > 0
      - vault_token | length > 0
      - vault_service_secrets_path | length > 0
      - vault_service_secrets is iterable
      - vault_service_secrets | length > 0
      - vault_service_secrets | selectattr('vault_name', 'undefined') | length == 0
      - vault_service_secrets | selectattr('ansible_name', 'undefined') | length == 0
      - vault_service_secrets | selectattr('file', 'undefined') | length == 0
    fail_msg: >-
      vault_service_secrets_path is required, vault_service_secrets must be array of {vault_name: "", ansible_name: "", file: ""}

- name: "[{{ vault_log_service_name }}] Read secret files"
  slurp:
    src: "{{ vault_secret.file }}"
  register: secret_files_raw
  loop: "{{ vault_service_secrets }}"
  loop_control:
    label: "{{ vault_secret.vault_name }}"
    loop_var: vault_secret
  no_log: true

- name: "[{{ vault_log_service_name }}] Build secrets dict"
  set_fact:
    service_secrets_data: >-
      {{
        dict(
          secret_files_raw.results
          | map(attribute='vault_secret.vault_name')
          | zip(
              secret_files_raw.results
              | map(attribute='content')
              | map('b64decode')
            )
        )
      }}
  no_log: true

- name: "[{{ vault_log_service_name }}] Write secrets"
  community.hashi_vault.vault_kv2_write:
    url: "{{ vault_addr }}"
    ca_cert: "{{ step_ca_system_ca_path }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ vault_kv_engine }}"
    path: "{{ vault_service_secrets_path }}"
    data: "{{ service_secrets_data }}"
  no_log: true